# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webshell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastexcude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='执行名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('shell', models.CharField(max_length=255, verbose_name='命令')),
                ('excude_time', models.DateTimeField(blank=True, null=True, verbose_name='最新执行时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='配置更新时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshell.webshell', verbose_name='执行服务器')),
            ],
        ),
    ]
