# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastexcude',
            name='status',
            field=models.BooleanField(default=False, verbose_name='执行状态'),
        ),
    ]
