# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0002_fastexcude_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastexcude',
            name='bar_data',
            field=models.IntegerField(default=0),
        ),
    ]
