# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0004_auto_20180925_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastexcudeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excudename', models.CharField(max_length=50, verbose_name='执行项')),
                ('excudeuser', models.CharField(max_length=50, verbose_name='执行人')),
                ('excude_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('excudestatus', models.BooleanField(default=False, verbose_name='执行结果')),
            ],
        ),
    ]
