# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0005_fastexcuderecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastexcuderecord',
            name='ipaddr',
            field=models.GenericIPAddressField(default='1', verbose_name='执行服务器'),
            preserve_default=False,
        ),
    ]
