# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0006_fastexcuderecord_ipaddr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastexcuderecord',
            old_name='ipaddr',
            new_name='excudeserver',
        ),
    ]
