# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_excute', '0008_fastexcuderecord_excudelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastexcuderecord',
            name='excudelog',
            field=models.TextField(blank=True, null=True, verbose_name='执行日志'),
        ),
    ]
