# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='负责人姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='负责人手机')),
                ('qq', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人QQ')),
                ('weChat', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人微信')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产品线名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品线描述')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目描述')),
                ('language_type', models.CharField(blank=True, choices=[('Java', 'Java'), ('PHP', 'PHP'), ('Python', 'Python'), ('C#', 'C#'), ('Html', 'Html'), ('Javascript', 'Javascript'), ('C/C++', 'C/C++'), ('Ruby', 'Ruby'), ('Other', 'Other')], max_length=30, null=True, verbose_name='语言类型')),
                ('app_type', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Middleware', 'Middleware'), ('Backend', 'Backend')], max_length=30, null=True, verbose_name='程序类型')),
                ('server_type', models.CharField(blank=True, choices=[('Tomcat', 'Tomcat'), ('Weblogic', 'Weblogic'), ('JETTY', 'JETTY'), ('Nginx', 'Nginx'), ('Gunicorn', 'Gunicorn'), ('Uwsgi', 'Uwsgi'), ('Apache', 'Apache'), ('IIS', 'IIS')], max_length=30, null=True, verbose_name='服务器类型')),
                ('app_arch', models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Tornado', 'Tornado'), ('Dubbo', 'Dubbo'), ('SSH', 'SSH'), ('Spring boot', 'Spring boot'), ('Spring cloud', 'Spring cloud'), ('Laravel', 'Laravel'), ('ThinkPHP', 'ThinkPHP'), ('Phalcon', 'Phalcon'), ('other', 'other')], max_length=30, null=True, verbose_name='程序框架')),
                ('source_type', models.CharField(blank=True, choices=[('git', 'git'), ('svn', 'svn')], max_length=255, verbose_name='源类型')),
                ('source_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='源地址')),
                ('appPath', models.CharField(blank=True, max_length=255, null=True, verbose_name='程序部署路径')),
                ('configPath', models.CharField(blank=True, max_length=255, null=True, verbose_name='配置文件路径')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.AppOwner', verbose_name='项目负责人')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='所属产品线')),
            ],
        ),
    ]
