# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_auto_20180823_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='server_type',
            field=models.CharField(blank=True, choices=[('Tomcat', 'Tomcat'), ('Resin', 'Resin'), ('Weblogic', 'Weblogic'), ('JETTY', 'JETTY'), ('Nginx', 'Nginx'), ('Gunicorn', 'Gunicorn'), ('Uwsgi', 'Uwsgi'), ('Apache', 'Apache'), ('IIS', 'IIS')], max_length=30, null=True, verbose_name='服务器类型'),
        ),
    ]
