# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_record', '0003_auto_20180903_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenrrecord',
            name='process_description',
            field=models.CharField(max_length=1024, verbose_name='处理过程'),
        ),
    ]
