# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0003_auto_20180823_1604'),
        ('broken_record', '0004_auto_20180903_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenrrecord',
            name='developer',
        ),
        migrations.AddField(
            model_name='brokenrrecord',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broken_record.Developer', verbose_name='开发主要处理人'),
        ),
        migrations.RemoveField(
            model_name='brokenrrecord',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='brokenrrecord',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appconf.AppOwner', verbose_name='运维主要处理人'),
        ),
    ]
