# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_record', '0005_auto_20180903_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_department',
            field=models.CharField(choices=[('Maintenance_department', 'Maintenance_department'), ('Technical_department', 'Technical_department'), ('other', 'other')], max_length=30, verbose_name='故障主要归属部门'),
        ),
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_type',
            field=models.CharField(choices=[('Network', '网络'), ('CDN', 'CDN'), ('Other', 'Other')], max_length=30, verbose_name='故障类型'),
        ),
    ]
