# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_record', '0006_auto_20180903_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_department',
            field=models.CharField(choices=[('Maintenance_department', '运维部'), ('Technical_department', '星星打车技术部'), ('other', '其他')], max_length=30, verbose_name='故障主要归属部门'),
        ),
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_status_type',
            field=models.CharField(choices=[('Solved', '已解决'), ('Processing', '处理中'), ('Shelving', '搁置中')], max_length=30, verbose_name='故障状态类型'),
        ),
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_type',
            field=models.CharField(choices=[('Network', '网络'), ('CDN', 'CDN缓存'), ('Database', '数据库'), ('WebContainer', 'Web容器'), ('Security', '安全漏洞'), ('Middleware', '中间件'), ('System', '操作系统'), ('Domain', '域名'), ('Hardware', '硬件'), ('Other', '其他')], max_length=30, verbose_name='故障类型'),
        ),
        migrations.AlterField(
            model_name='brokenrrecord',
            name='severity_type',
            field=models.CharField(choices=[('Serious', '非常高'), ('High', '高'), ('Medium', '中'), ('Low', '低')], max_length=30, verbose_name='故障严重性'),
        ),
    ]
