# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_record', '0007_auto_20180903_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_type',
            field=models.CharField(choices=[('网络', '网络'), ('CDN', 'CDN缓存'), ('Database', '数据库'), ('WebContainer', 'Web容器'), ('Security', '安全漏洞'), ('Middleware', '中间件'), ('System', '操作系统'), ('Domain', '域名'), ('Hardware', '硬件'), ('Other', '其他')], max_length=30, verbose_name='故障类型'),
        ),
    ]
