# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_record', '0009_auto_20180903_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenrrecord',
            name='broken_type',
            field=models.CharField(choices=[('网络', '网络'), ('CDN缓存', 'CDN缓存'), ('数据库', '数据库'), ('Web容器', 'Web容器'), ('安全漏洞', '安全漏洞'), ('中间件', '中间件'), ('操作系统', '操作系统'), ('域名', '域名'), ('硬件', '硬件'), ('代码BUG', '代码BUG'), ('人为误操作', '人为误操作'), ('其他', '其他')], max_length=30, verbose_name='故障类型'),
        ),
    ]
