# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='机房地址'),
        ),
        migrations.AddField(
            model_name='idc',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='接入带宽'),
        ),
        migrations.AddField(
            model_name='idc',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='客户经理'),
        ),
        migrations.AddField(
            model_name='idc',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='移动电话'),
        ),
        migrations.AddField(
            model_name='idc',
            name='ids',
            field=models.CharField(default='ZSLT-01', max_length=255, unique=True, verbose_name='机房标识'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idc',
            name='ip_range',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP范围'),
        ),
        migrations.AddField(
            model_name='idc',
            name='jigui',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜信息'),
        ),
        migrations.AddField(
            model_name='idc',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机房电话'),
        ),
    ]
