# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-06 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(verbose_name='登录时间')),
                ('loginsource', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录来源IP')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
        ),
    ]
