# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_loginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='logintime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
    ]
