# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktype', models.CharField(max_length=50, verbose_name='任务类型')),
                ('taskuser', models.CharField(max_length=50, verbose_name='执行人')),
                ('tasktime', models.DateTimeField(verbose_name='执行时间')),
                ('taskstatus', models.BooleanField(default=False, verbose_name='执行结果')),
                ('taskinfo', models.TextField(verbose_name='执行详情')),
            ],
        ),
    ]
