# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='测试字段'),
        ),
    ]
