# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, unique=True, verbose_name='域')),
                ('name', models.CharField(max_length=50, verbose_name='域名地址')),
                ('ctime', models.DateTimeField(verbose_name='域名创建时间')),
                ('etime', models.DateTimeField(verbose_name='域名过期时间')),
                ('ip', models.GenericIPAddressField(verbose_name='域名解析IP')),
                ('ip_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='解析IP来源')),
                ('domain_record_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='域名备案号')),
                ('domain_nature', models.CharField(blank=True, max_length=50, null=True, verbose_name='域名性质')),
                ('domain_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='域名所属公司')),
            ],
        ),
    ]
