# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastexcudeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50, unique=True, verbose_name='监控图组名称')),
                ('graphids', models.CharField(max_length=256, verbose_name='成员图片id（逗号分隔）')),
            ],
        ),
    ]
