# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FastexcudeRecord',
            new_name='MonitorGraph',
        ),
    ]
